"""Deliverable store implementation for SWARAJ maker-checker workflow."""

import json
import time
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from typing import Any
import aiosqlite
from approval.service import ApprovalService


class DeliverableStore:
    """Manages creation, query, field verification, and approval lifecycle of deliverables."""

    def __init__(self, db_path: str, approval_service: ApprovalService | None = None) -> None:
        self.db_path = str(db_path)
        self.approval_service = approval_service or ApprovalService()

    @asynccontextmanager
    async def _get_connection(self) -> AsyncIterator[aiosqlite.Connection]:
        async with aiosqlite.connect(self.db_path) as conn:
            conn.row_factory = aiosqlite.Row
            await conn.execute("PRAGMA foreign_keys = OFF;")
            yield conn

    async def create_deliverable(self, deliverable: dict[str, Any]) -> dict[str, Any]:
        """Save a new deliverable generated by the agent or user into SQLite."""
        now_ms = int(time.time() * 1000)
        d_id = deliverable.get("id") or f"DELIV-{int(time.time())}"
        project_id = deliverable.get("projectId") or deliverable.get("project_id", "default-project")
        session_id = deliverable.get("sessionId") or deliverable.get("session_id", "default-session")
        title = deliverable.get("title", "Technical Deliverable")
        subject = deliverable.get("subject", title)
        status = deliverable.get("status", "PENDING_CHECK")
        org_config = deliverable.get("orgConfig", {})
        maker = deliverable.get("maker", {"id": "user_maker", "name": "Engineer", "designation": "Inspection Engineer"})
        checker = deliverable.get("checker", {"id": "user_checker", "name": "Approver", "designation": "Chief Engineer"})
        narrative = deliverable.get("narrative", "")
        fields = deliverable.get("fields", [])
        citations = deliverable.get("citations", [])
        calc_execution = deliverable.get("calcExecution") or deliverable.get("calc_execution", {})
        models_used = deliverable.get("modelsUsed") or deliverable.get("models_used", [])

        async with self._get_connection() as conn:
            await conn.execute(
                """
                INSERT OR REPLACE INTO deliverables (
                    id, project_id, session_id, title, subject, status,
                    org_config_json, maker_json, checker_json, narrative,
                    fields_json, citations_json, calc_execution_json,
                    models_used_json, stamp_text, audit_record_id,
                    created_at_ms, updated_at_ms
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    d_id,
                    project_id,
                    session_id,
                    title,
                    subject,
                    status,
                    json.dumps(org_config),
                    json.dumps(maker),
                    json.dumps(checker),
                    narrative,
                    json.dumps(fields),
                    json.dumps(citations),
                    json.dumps(calc_execution),
                    json.dumps(models_used),
                    "",
                    None,
                    now_ms,
                    now_ms,
                ),
            )
            await conn.commit()

        return await self.get_deliverable(d_id)  # type: ignore

    async def list_deliverables(self, project_id: str | None = None, session_id: str | None = None) -> list[dict[str, Any]]:
        """List deliverables for project or session."""
        async with self._get_connection() as conn:
            if session_id:
                cursor = await conn.execute(
                    "SELECT id, project_id, session_id, title, subject, status, updated_at_ms FROM deliverables WHERE session_id = ? ORDER BY updated_at_ms DESC",
                    (session_id,),
                )
            elif project_id:
                cursor = await conn.execute(
                    "SELECT id, project_id, session_id, title, subject, status, updated_at_ms FROM deliverables WHERE project_id = ? ORDER BY updated_at_ms DESC",
                    (project_id,),
                )
            else:
                cursor = await conn.execute(
                    "SELECT id, project_id, session_id, title, subject, status, updated_at_ms FROM deliverables ORDER BY updated_at_ms DESC"
                )
            rows = await cursor.fetchall()
            return [dict(r) for r in rows]

    async def get_deliverable(self, deliverable_id: str) -> dict[str, Any] | None:
        """Fetch complete deliverable details."""
        async with self._get_connection() as conn:
            cursor = await conn.execute(
                "SELECT * FROM deliverables WHERE id = ?",
                (deliverable_id,),
            )
            row = await cursor.fetchone()
            if not row:
                return None
            data = dict(row)
            return {
                "id": data["id"],
                "deliverableId": data["id"],
                "projectId": data["project_id"],
                "sessionId": data["session_id"],
                "title": data["title"],
                "subject": data["subject"],
                "status": data["status"],
                "orgConfig": json.loads(data["org_config_json"]),
                "maker": json.loads(data["maker_json"]),
                "checker": json.loads(data["checker_json"]),
                "narrative": data["narrative"],
                "fields": json.loads(data["fields_json"]),
                "citations": json.loads(data["citations_json"]),
                "calcExecution": json.loads(data["calc_execution_json"]),
                "modelsUsed": json.loads(data["models_used_json"]),
                "stampText": data["stamp_text"],
                "auditRecordId": data["audit_record_id"],
                "createdAtMs": data["created_at_ms"],
                "updatedAtMs": data["updated_at_ms"],
            }

    async def verify_field(self, deliverable_id: str, field_id: str, verified_by: str | None = None) -> dict[str, Any]:
        """Mark a field as verified by human reviewer."""
        async with self._get_connection() as conn:
            cursor = await conn.execute("SELECT fields_json FROM deliverables WHERE id = ?", (deliverable_id,))
            row = await cursor.fetchone()
            if not row:
                raise ValueError(f"Deliverable '{deliverable_id}' not found")

            fields = json.loads(row["fields_json"])
            for f in fields:
                if f.get("id") == field_id:
                    f["is_verified"] = True
                    f["requires_verification"] = False
                    if verified_by:
                        f["verified_by"] = verified_by

            now_ms = int(time.time() * 1000)
            await conn.execute(
                "UPDATE deliverables SET fields_json = ?, updated_at_ms = ? WHERE id = ?",
                (json.dumps(fields), now_ms, deliverable_id),
            )
            await conn.commit()
            return await self.get_deliverable(deliverable_id)  # type: ignore

    async def cite_claim(self, deliverable_id: str, citation_id: str) -> dict[str, Any]:
        """Confirm citation grounding for standard claim."""
        async with self._get_connection() as conn:
            cursor = await conn.execute("SELECT citations_json FROM deliverables WHERE id = ?", (deliverable_id,))
            row = await cursor.fetchone()
            if not row:
                raise ValueError(f"Deliverable '{deliverable_id}' not found")

            citations = json.loads(row["citations_json"])
            for c in citations:
                if c.get("id") == citation_id:
                    c["is_cited"] = True

            now_ms = int(time.time() * 1000)
            await conn.execute(
                "UPDATE deliverables SET citations_json = ?, updated_at_ms = ? WHERE id = ?",
                (json.dumps(citations), now_ms, deliverable_id),
            )
            await conn.commit()
            return await self.get_deliverable(deliverable_id)  # type: ignore

    async def update_narrative(self, deliverable_id: str, edited_narrative: str) -> dict[str, Any]:
        """Update draft narrative text."""
        async with self._get_connection() as conn:
            now_ms = int(time.time() * 1000)
            await conn.execute(
                "UPDATE deliverables SET narrative = ?, updated_at_ms = ? WHERE id = ?",
                (edited_narrative, now_ms, deliverable_id),
            )
            await conn.commit()
            return await self.get_deliverable(deliverable_id)  # type: ignore

    async def approve(
        self,
        deliverable_id: str,
        checker: dict[str, str] | None = None,
        checker_id: str | None = None,
        checker_name: str | None = None,
        checker_designation: str | None = None,
        stamp_text: str | None = None,
        edited_narrative: str | None = None,
    ) -> dict[str, Any]:
        """Approve deliverable through ApprovalService maker-checker validation."""
        d = await self.get_deliverable(deliverable_id)
        if not d:
            raise ValueError(f"Deliverable '{deliverable_id}' not found")

        fields = d["fields"]
        citations = d["citations"]
        calc = d["calcExecution"]
        maker = d["maker"]
        org_config = d["orgConfig"]

        c_id = checker_id or (checker.get("id") if checker else "user_checker")
        c_name = checker_name or (checker.get("name") if checker else "Checker")
        c_desig = checker_designation or (checker.get("designation") if checker else "Authority")

        unverified_count = sum(1 for f in fields if not f.get("is_verified", False))
        uncited_count = sum(1 for c in citations if not c.get("is_cited", False))
        calc_status = calc.get("status", "VERIFIED")

        orig_narrative = d["narrative"]
        final_narrative = edited_narrative if edited_narrative is not None else orig_narrative

        approval_res = self.approval_service.approve_deliverable(
            deliverable_id=deliverable_id,
            maker_id=maker["id"],
            checker_id=c_id,
            checker_name=c_name,
            checker_designation=c_desig,
            unverified_fields_count=unverified_count,
            uncited_claims_count=uncited_count,
            calc_verification_status=calc_status,
            original_text=orig_narrative,
            edited_text=final_narrative,
            org_terminology=org_config.get("terminology", "APPROVED"),
        )

        final_stamp = stamp_text if stamp_text else approval_res.stamp_text

        now_ms = int(time.time() * 1000)
        async with self._get_connection() as conn:
            await conn.execute(
                """
                UPDATE deliverables
                SET status = 'APPROVED',
                    narrative = ?,
                    stamp_text = ?,
                    audit_record_id = ?,
                    updated_at_ms = ?
                WHERE id = ?
                """,
                (
                    final_narrative,
                    final_stamp,
                    approval_res.audit_record.audit_id,
                    now_ms,
                    deliverable_id,
                ),
            )
            await conn.commit()

        updated = await self.get_deliverable(deliverable_id)
        return {
            "status": "APPROVED",
            "stamp_text": final_stamp,
            "deliverable": updated,
            "approvalResult": {
                "status": approval_res.status,
                "approvedBy": approval_res.approved_by,
                "checkerDesignation": approval_res.checker_designation,
                "stampText": final_stamp,
                "approvedAt": approval_res.approved_at,
                "auditRecord": {
                    "auditId": approval_res.audit_record.audit_id,
                    "action": approval_res.audit_record.action,
                    "maker": maker,
                    "checker": {
                        "id": c_id,
                        "name": c_name,
                        "designation": c_desig,
                    },
                    "timestamp": approval_res.audit_record.timestamp,
                    "stampText": final_stamp,
                    "wordDiffs": approval_res.audit_record.word_diffs,
                },
            },
        }

    async def reject(
        self,
        deliverable_id: str,
        checker: dict[str, str] | None = None,
        checker_id: str | None = None,
        checker_name: str | None = None,
        checker_designation: str | None = None,
        reason: str = "",
    ) -> dict[str, Any]:
        """Reject deliverable with mandatory audit trail reason."""
        d = await self.get_deliverable(deliverable_id)
        if not d:
            raise ValueError(f"Deliverable '{deliverable_id}' not found")

        maker = d["maker"]
        c_id = checker_id or (checker.get("id") if checker else "user_checker")
        c_name = checker_name or (checker.get("name") if checker else "Checker")
        c_desig = checker_designation or (checker.get("designation") if checker else "Authority")

        rejection_res = self.approval_service.reject_deliverable(
            deliverable_id=deliverable_id,
            maker_id=maker["id"],
            checker_id=c_id,
            checker_name=c_name,
            checker_designation=c_desig,
            reason=reason,
        )

        now_ms = int(time.time() * 1000)
        async with self._get_connection() as conn:
            await conn.execute(
                """
                UPDATE deliverables
                SET status = 'REJECTED',
                    audit_record_id = ?,
                    updated_at_ms = ?
                WHERE id = ?
                """,
                (
                    rejection_res.audit_record.audit_id,
                    now_ms,
                    deliverable_id,
                ),
            )
            await conn.commit()

        updated = await self.get_deliverable(deliverable_id)
        return {
            "status": "REJECTED",
            "deliverable": updated,
            "rejectionResult": {
                "status": rejection_res.status,
                "rejectedBy": rejection_res.rejected_by,
                "reason": rejection_res.reason,
                "rejectedAt": rejection_res.rejected_at,
                "auditRecord": {
                    "auditId": rejection_res.audit_record.audit_id,
                    "action": rejection_res.audit_record.action,
                    "maker": maker,
                    "checker": {
                        "id": c_id,
                        "name": c_name,
                        "designation": c_desig,
                    },
                    "timestamp": rejection_res.audit_record.timestamp,
                    "reason": rejection_res.audit_record.rejection_reason,
                },
            },
        }
