"""Base tool abstractions and execution context."""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path
from typing import Any, TypeVar

from pydantic import BaseModel


class SideEffect(StrEnum):
    """Static classification of a tool's side-effect capability."""

    READ = "read"
    WRITE = "write"
    EXEC = "exec"


class ToolKind(StrEnum):
    """Tool capability kind matching protocol specification."""

    READ = "read"
    EDIT = "edit"
    DELETE = "delete"
    MOVE = "move"
    SEARCH = "search"
    EXECUTE = "execute"
    THINK = "think"
    FETCH = "fetch"
    OTHER = "other"


@dataclass
class ToolContext:
    """Execution context provided to tools during execution."""

    workspace_root: Path
    session_id: str = "default"


@dataclass
class ToolResult:
    """Standard execution result returned by all tools."""

    success: bool
    output: Any = None
    error: str | None = None

    @classmethod
    def ok(cls, output: Any) -> "ToolResult":
        return cls(success=True, output=output)

    @classmethod
    def failed(cls, error: str, output: Any = None) -> "ToolResult":
        return cls(success=False, output=output, error=error)


InputModelT = TypeVar("InputModelT", bound=BaseModel)
OutputModelT = TypeVar("OutputModelT", bound=BaseModel)


class BaseTool[InputModelT: BaseModel, OutputModelT: BaseModel](ABC):
    """Abstract base class for all typed SWARAJ agent tools."""

    name: str
    description: str
    kind: ToolKind
    side_effect: SideEffect
    scopes: list[str]
    timeout_s: float
    is_idempotent: bool
    input_model: type[InputModelT]
    output_model: type[OutputModelT]

    def to_ollama_tool(self) -> dict[str, Any]:
        """Derive the Ollama function tool JSON Schema automatically from input_model."""
        schema = self.input_model.model_json_schema()
        # Remove title if generated by pydantic to keep schema clean for local models
        schema.pop("title", None)
        return {
            "type": "function",
            "function": {
                "name": self.name,
                "description": self.description,
                "parameters": schema,
            },
        }

    @abstractmethod
    async def run(self, args: InputModelT, ctx: ToolContext) -> ToolResult:
        """Execute the tool with validated arguments and context."""
        ...
