"""Native AST Script Builders for Sandbox Document Generation.

Generates sandboxed Python scripts that emit native Word (python-docx), PDF (ReportLab),
Excel (openpyxl), and PowerPoint (python-pptx) elements conforming to SWARAJ design tokens.
"""

import json
import re

HYPHEN_REPLACEMENTS = {
    "\u2011": "-", "\u2010": "-", "\u00AD": "-", "\u2012": "-", "\u2212": "-",
    "\uFE63": "-", "\uFF0D": "-", "\u2043": "-", "\u25A0": "-", "\u25AA": "-",
    "\u25FE": "-", "\u25FD": "-", "\u00A0": " ", "\u202F": " ", "\u2007": " ",
    "\u2008": " ", "\u2009": " ", "\u200A": " ", "\u200B": "", "\uFEFF": "",
}

HYPHEN_MAP_CODE = (
    "HYPHEN_MAP = {'\\u2011': '-', '\\u2010': '-', '\\u00AD': '-', '\\u2012': '-', "
    "'\\u2212': '-', '\\uFE63': '-', '\\uFF0D': '-', '\\u2043': '-', "
    "'\\u25A0': '-', '\\u25AA': '-', '\\u25FE': '-', '\\u25FD': '-', "
    "'\\u00A0': ' ', '\\u202F': ' ', '\\u200B': '', '\\uFEFF': ''}\n\n"
    "def clean_line(t):\n"
    "    if not t: return ''\n"
    "    for k, v in HYPHEN_MAP.items(): t = t.replace(k, v)\n"
    "    if not (t.strip().startswith('|') and t.strip().endswith('|')):\n"
    "        t = re.sub(r'\\s*\\|\\s*$', '', t)\n"
    "    return t\n"
)


def normalize_typographic_punctuation(text: str) -> str:
    """Normalize typography control characters and non-standard hyphens."""
    if not text:
        return ""
    for bad, good in HYPHEN_REPLACEMENTS.items():
        text = text.replace(bad, good)
    return text


def build_pdf_script(declared_name: str, content: str) -> str:
    """Generate sandboxed Python script emitting a styled PDF via ReportLab."""
    escaped = json.dumps(normalize_typographic_punctuation(content))
    return (
        "import os, sys, json, re\n"
        "from reportlab.lib.pagesizes import letter\n"
        "from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle\n"
        "from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle\n"
        "from reportlab.lib import colors\n\n"
        f"{HYPHEN_MAP_CODE}\n"
        "def main():\n"
        "    out_dir = os.environ.get('SWARAJ_OUT_DIR', './out')\n"
        "    os.makedirs(out_dir, exist_ok=True)\n"
        f"    out_path = os.path.join(out_dir, {json.dumps(declared_name)})\n"
        "    doc = SimpleDocTemplate(out_path, pagesize=letter, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)\n"
        "    styles = getSampleStyleSheet()\n"
        "    h1_style = ParagraphStyle('H1', parent=styles['Heading1'], fontSize=16, leading=20, textColor=colors.HexColor('#0B62D6'))\n"
        "    h2_style = ParagraphStyle('H2', parent=styles['Heading2'], fontSize=13, leading=17, textColor=colors.HexColor('#0B62D6'))\n"
        "    h3_style = ParagraphStyle('H3', parent=styles['Heading3'], fontSize=11, leading=15, textColor=colors.HexColor('#1F2328'))\n"
        "    body_style = ParagraphStyle('Body', parent=styles['Normal'], fontSize=10, leading=14, textColor=colors.HexColor('#1F2328'))\n"
        "    story, lines = [], " f"{escaped}.splitlines()\n"
        "    i = 0\n"
        "    while i < len(lines):\n"
        "        line = clean_line(lines[i])\n"
        "        trimmed = line.strip()\n"
        "        if not trimmed:\n"
        "            story.append(Spacer(1, 6)); i += 1; continue\n"
        "        if trimmed.startswith('# '):\n"
        "            story.append(Paragraph(trimmed[2:], h1_style)); story.append(Spacer(1, 8))\n"
        "        elif trimmed.startswith('## '):\n"
        "            story.append(Paragraph(trimmed[3:], h2_style)); story.append(Spacer(1, 6))\n"
        "        elif trimmed.startswith('### '):\n"
        "            story.append(Paragraph(trimmed[4:], h3_style)); story.append(Spacer(1, 4))\n"
        "        elif trimmed.startswith(('- ', '* ')):\n"
        "            clean_b = re.sub(r'\\*\\*(.+?)\\*\\*', r'<b>\\1</b>', trimmed[2:])\n"
        "            story.append(Paragraph(f'&bull; {clean_b}', body_style)); story.append(Spacer(1, 3))\n"
        "        elif re.match(r'^\\d+\\.\\s', trimmed):\n"
        "            clean_num = re.sub(r'\\*\\*(.+?)\\*\\*', r'<b>\\1</b>', trimmed)\n"
        "            story.append(Paragraph(clean_num, body_style)); story.append(Spacer(1, 3))\n"
        "        elif trimmed.startswith('|') and trimmed.endswith('|'):\n"
        "            table_data = []\n"
        "            while i < len(lines) and clean_line(lines[i]).strip().startswith('|') and clean_line(lines[i]).strip().endswith('|'):\n"
        "                row_str = clean_line(lines[i]).strip()\n"
        "                if not re.match(r'\\|[\\s\\-:]+\\|', row_str):\n"
        "                    cells = [c.strip() for c in row_str.strip('|').split('|')]\n"
        "                    table_data.append([Paragraph(re.sub(r'\\*\\*(.+?)\\*\\*', r'<b>\\1</b>', c), body_style) for c in cells])\n"
        "                i += 1\n"
        "            if table_data:\n"
        "                t = Table(table_data)\n"
        "                t.setStyle(TableStyle([\n"
        "                    ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#F6F8FA')),\n"
        "                    ('BOTTOMPADDING', (0,0), (-1,-1), 4), ('TOPPADDING', (0,0), (-1,-1), 4),\n"
        "                    ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#D0D7DE')),\n"
        "                ]))\n"
        "                story.append(t); story.append(Spacer(1, 8))\n"
        "            continue\n"
        "        else:\n"
        "            clean_p = re.sub(r'\\*\\*(.+?)\\*\\*', r'<b>\\1</b>', trimmed)\n"
        "            story.append(Paragraph(clean_p, body_style)); story.append(Spacer(1, 4))\n"
        "        i += 1\n"
        "    doc.build(story)\n\n"
        "if __name__ == '__main__':\n"
        "    main()\n"
    )


def build_docx_script(declared_name: str, content: str) -> str:
    """Generate sandboxed Python script emitting native DOCX elements."""
    escaped = json.dumps(normalize_typographic_punctuation(content))
    return (
        "import os, sys, json, re\n"
        "from docx import Document\n"
        "from docx.shared import Inches, Pt, RGBColor\n"
        "from docx.oxml import OxmlElement\n"
        "from docx.oxml.ns import qn\n\n"
        f"{HYPHEN_MAP_CODE}\n"
        "def apply_fonts(doc):\n"
        "    style = doc.styles['Normal']\n"
        "    style.font.name, style.font.size = 'Calibri', Pt(11)\n"
        "    style.font.color.rgb = RGBColor(0x1F, 0x23, 0x28)\n"
        "    rPr = style.element.get_or_add_rPr()\n"
        "    rFonts = rPr.find(qn('w:rFonts'))\n"
        "    if rFonts is None:\n"
        "        rFonts = OxmlElement('w:rFonts'); rPr.append(rFonts)\n"
        "    rFonts.set(qn('w:ascii'), 'Calibri'); rFonts.set(qn('w:hAnsi'), 'Calibri')\n"
        "    rFonts.set(qn('w:cs'), 'Noto Sans Devanagari')\n\n"
        "def add_formatted_runs(p, text):\n"
        "    for part in re.split(r'(\\*\\*.*?\\*\\*)', clean_line(text)):\n"
        "        if part.startswith('**') and part.endswith('**'):\n"
        "            r = p.add_run(part[2:-2]); r.bold = True\n"
        "        else: p.add_run(part)\n\n"
        "def main():\n"
        "    out_dir = os.environ.get('SWARAJ_OUT_DIR', './out')\n"
        "    os.makedirs(out_dir, exist_ok=True)\n"
        f"    out_path = os.path.join(out_dir, {json.dumps(declared_name)})\n"
        "    doc = Document()\n"
        "    apply_fonts(doc)\n"
        "    for s in doc.sections:\n"
        "        s.top_margin = s.bottom_margin = s.left_margin = s.right_margin = Inches(0.75)\n"
        "    lines = " f"{escaped}.splitlines()\n"
        "    i = 0\n"
        "    while i < len(lines):\n"
        "        line = clean_line(lines[i])\n"
        "        trimmed = line.strip()\n"
        "        if not trimmed: i += 1; continue\n"
        "        if trimmed.startswith('# '):\n"
        "            h = doc.add_heading(level=1); add_formatted_runs(h, trimmed[2:])\n"
        "            if h.runs: h.runs[0].font.color.rgb = RGBColor(0x0B, 0x62, 0xD6)\n"
        "        elif trimmed.startswith('## '):\n"
        "            h = doc.add_heading(level=2); add_formatted_runs(h, trimmed[3:])\n"
        "            if h.runs: h.runs[0].font.color.rgb = RGBColor(0x0B, 0x62, 0xD6)\n"
        "        elif trimmed.startswith('### '):\n"
        "            h = doc.add_heading(level=3); add_formatted_runs(h, trimmed[4:])\n"
        "        elif trimmed.startswith(('- ', '* ')):\n"
        "            p = doc.add_paragraph(style='List Bullet'); add_formatted_runs(p, trimmed[2:])\n"
        "        elif re.match(r'^\\d+\\.\\s', trimmed):\n"
        "            p = doc.add_paragraph(); add_formatted_runs(p, trimmed)\n"
        "        elif trimmed.startswith('|') and trimmed.endswith('|'):\n"
        "            table_lines = []\n"
        "            while i < len(lines) and clean_line(lines[i]).strip().startswith('|') and clean_line(lines[i]).strip().endswith('|'):\n"
        "                row_str = clean_line(lines[i]).strip()\n"
        "                if not re.match(r'\\|[\\s\\-:]+\\|', row_str):\n"
        "                    table_lines.append([c.strip() for c in row_str.strip('|').split('|')])\n"
        "                i += 1\n"
        "            if table_lines:\n"
        "                cols = max(len(r) for r in table_lines)\n"
        "                tbl = doc.add_table(rows=len(table_lines), cols=cols)\n"
        "                tbl.style = 'Table Grid'\n"
        "                for r_idx, r_data in enumerate(table_lines):\n"
        "                    for c_idx, c_text in enumerate(r_data):\n"
        "                        if c_idx < cols:\n"
        "                            cell = tbl.rows[r_idx].cells[c_idx]\n"
        "                            cell.text = ''; cp = cell.paragraphs[0]; add_formatted_runs(cp, c_text)\n"
        "                            if r_idx == 0:\n"
        "                                for r in cp.runs: r.bold = True\n"
        "            continue\n"
        "        else:\n"
        "            p = doc.add_paragraph(); add_formatted_runs(p, trimmed)\n"
        "        i += 1\n"
        "    doc.save(out_path)\n\n"
        "if __name__ == '__main__':\n"
        "    main()\n"
    )


def build_pptx_script(declared_name: str, content: str) -> str:
    """Generate sandboxed Python script emitting native PowerPoint slides via python-pptx."""
    escaped = json.dumps(normalize_typographic_punctuation(content))
    return (
        "import os, sys, json, re\n"
        "from pptx import Presentation\n"
        "from pptx.util import Inches, Pt\n"
        "from pptx.dml.color import RGBColor\n\n"
        f"{HYPHEN_MAP_CODE}\n"
        "def strip_md(t):\n"
        "    return re.sub(r'\\*\\*(.+?)\\*\\*', r'\\1', clean_line(t)).strip()\n\n"
        "def main():\n"
        "    out_dir = os.environ.get('SWARAJ_OUT_DIR', './out')\n"
        "    os.makedirs(out_dir, exist_ok=True)\n"
        f"    out_path = os.path.join(out_dir, {json.dumps(declared_name)})\n"
        "    prs = Presentation()\n"
        "    prs.slide_width, prs.slide_height = Inches(13.333), Inches(7.5)\n"
        "    lines = " f"{escaped}.splitlines()\n"
        "    blank_layout = prs.slide_layouts[6]\n"
        "    current_slide, current_tf = None, None\n"
        "    i = 0\n"
        "    while i < len(lines):\n"
        "        line = clean_line(lines[i])\n"
        "        trimmed = line.strip()\n"
        "        if not trimmed: i += 1; continue\n"
        "        if trimmed.startswith('# ') and current_slide is None:\n"
        "            current_slide = prs.slides.add_slide(prs.slide_layouts[0])\n"
        "            current_slide.shapes.title.text = strip_md(trimmed[2:])\n"
        "            current_tf = None\n"
        "        elif trimmed.startswith(('## ', '# ', '### ')):\n"
        "            heading_text = strip_md(re.sub(r'^#{1,3}\\s*', '', trimmed))\n"
        "            current_slide = prs.slides.add_slide(blank_layout)\n"
        "            hb = current_slide.shapes.add_textbox(Inches(0.8), Inches(0.6), Inches(11.7), Inches(0.8))\n"
        "            hp = hb.text_frame.paragraphs[0]; hp.text = heading_text; hp.font.size = Pt(22)\n"
        "            hp.font.bold = True; hp.font.color.rgb = RGBColor(0x0B, 0x62, 0xD6)\n"
        "            cb = current_slide.shapes.add_textbox(Inches(0.8), Inches(1.6), Inches(11.7), Inches(5.0))\n"
        "            current_tf = cb.text_frame; current_tf.word_wrap = True\n"
        "        elif trimmed.startswith(('- ', '* ')):\n"
        "            if current_tf is None:\n"
        "                current_slide = prs.slides.add_slide(blank_layout)\n"
        "                cb = current_slide.shapes.add_textbox(Inches(0.8), Inches(1.0), Inches(11.7), Inches(5.5))\n"
        "                current_tf = cb.text_frame; current_tf.word_wrap = True\n"
        "            p = current_tf.add_paragraph() if current_tf.paragraphs and current_tf.paragraphs[0].text else current_tf.paragraphs[0]\n"
        "            p.text = f'• {strip_md(trimmed[2:])}'; p.font.size = Pt(14); p.font.color.rgb = RGBColor(0x1F, 0x23, 0x28)\n"
        "        elif trimmed.startswith('|') and trimmed.endswith('|'):\n"
        "            table_lines = []\n"
        "            while i < len(lines) and clean_line(lines[i]).strip().startswith('|') and clean_line(lines[i]).strip().endswith('|'):\n"
        "                row_str = clean_line(lines[i]).strip()\n"
        "                if not re.match(r'\\|[\\s\\-:]+\\|', row_str):\n"
        "                    table_lines.append([strip_md(c) for c in row_str.strip('|').split('|')])\n"
        "                i += 1\n"
        "            if table_lines:\n"
        "                if current_slide is None: current_slide = prs.slides.add_slide(blank_layout)\n"
        "                cols = max(len(r) for r in table_lines)\n"
        "                t_shape = current_slide.shapes.add_table(len(table_lines), cols, Inches(0.8), Inches(2.2), Inches(11.7), Inches(3.5))\n"
        "                for r_idx, r_data in enumerate(table_lines):\n"
        "                    for c_idx, c_text in enumerate(r_data):\n"
        "                        if c_idx < cols: t_shape.table.cell(r_idx, c_idx).text = c_text\n"
        "            continue\n"
        "        else:\n"
        "            if current_tf is None:\n"
        "                current_slide = prs.slides.add_slide(blank_layout)\n"
        "                cb = current_slide.shapes.add_textbox(Inches(0.8), Inches(1.0), Inches(11.7), Inches(5.5))\n"
        "                current_tf = cb.text_frame; current_tf.word_wrap = True\n"
        "            p = current_tf.add_paragraph() if current_tf.paragraphs and current_tf.paragraphs[0].text else current_tf.paragraphs[0]\n"
        "            p.text = strip_md(trimmed); p.font.size = Pt(13); p.font.color.rgb = RGBColor(0x1F, 0x23, 0x28)\n"
        "        i += 1\n"
        "    if len(prs.slides) == 0:\n"
        "        s = prs.slides.add_slide(blank_layout)\n"
        "        s.shapes.add_textbox(Inches(1.0), Inches(1.0), Inches(11.3), Inches(4.0)).text_frame.text = 'Presentation'\n"
        "    prs.save(out_path)\n\n"
        "if __name__ == '__main__':\n"
        "    main()\n"
    )


def build_xlsx_script(declared_name: str, content: str) -> str:
    """Generate sandboxed Python script emitting native Excel spreadsheet via openpyxl."""
    escaped = json.dumps(normalize_typographic_punctuation(content))
    return (
        "import os, sys, json, re\n"
        "from openpyxl import Workbook\n"
        "from openpyxl.styles import Font, PatternFill, Border, Side\n"
        "from openpyxl.utils import get_column_letter\n\n"
        f"{HYPHEN_MAP_CODE}\n"
        "def clean_val(v):\n"
        "    if not v: return ''\n"
        "    v = re.sub(r'\\*\\*(.+?)\\*\\*', r'\\1', clean_line(v)).strip()\n"
        "    if re.match(r'^-?\\d+$', v): return int(v)\n"
        "    if re.match(r'^-?\\d+\\.\\d+$', v): return float(v)\n"
        "    return v\n\n"
        "def main():\n"
        "    out_dir = os.environ.get('SWARAJ_OUT_DIR', './out')\n"
        "    os.makedirs(out_dir, exist_ok=True)\n"
        f"    out_path = os.path.join(out_dir, {json.dumps(declared_name)})\n"
        "    wb = Workbook()\n"
        "    ws = wb.active; ws.title = 'Data'\n"
        "    lines = " f"{escaped}.splitlines()\n"
        "    hdr_fill = PatternFill(start_color='F6F8FA', end_color='F6F8FA', fill_type='solid')\n"
        "    hdr_font = Font(name='Calibri', size=11, bold=True, color='1F2328')\n"
        "    body_font = Font(name='Calibri', size=11, color='1F2328')\n"
        "    thin = Border(left=Side(style='thin', color='D0D7DE'), right=Side(style='thin', color='D0D7DE'), top=Side(style='thin', color='D0D7DE'), bottom=Side(style='thin', color='D0D7DE'))\n"
        "    row_num, has_tbl = 1, False\n"
        "    for line in lines:\n"
        "        line = line.strip()\n"
        "        if line.startswith('|') and line.endswith('|'):\n"
        "            if re.match(r'\\|[\\s\\-:]+\\|', line): continue\n"
        "            cells = [clean_val(c) for c in line.strip('|').split('|')]\n"
        "            for col_idx, val in enumerate(cells, 1):\n"
        "                cell = ws.cell(row=row_num, column=col_idx, value=val)\n"
        "                cell.border = thin\n"
        "                cell.fill, cell.font = (hdr_fill, hdr_font) if not has_tbl else (PatternFill(fill_type=None), body_font)\n"
        "            has_tbl = True; row_num += 1\n"
        "        elif line and not line.startswith('#'):\n"
        "            val = clean_val(line.lstrip('-* '))\n"
        "            ws.cell(row=row_num, column=1, value=val).font = body_font\n"
        "            row_num += 1\n"
        "    if row_num == 1:\n"
        "        ws.cell(row=1, column=1, value='Data Sheet').font = hdr_font\n"
        "    for col in ws.columns:\n"
        "        col_letter = get_column_letter(col[0].column)\n"
        "        max_len = max(len(str(c.value or '')) for c in col)\n"
        "        ws.column_dimensions[col_letter].width = max(max_len + 4, 12)\n"
        "    wb.save(out_path)\n\n"
        "if __name__ == '__main__':\n"
        "    main()\n"
    )
