"""Native AST Script Builders for Sandbox Document Generation.

Generates sandboxed Python scripts that emit native Word (python-docx), PDF (ReportLab),
and Excel (openpyxl) elements conforming to SWARAJ design tokens and complex script standards.
"""

import json
import re

HYPHEN_REPLACEMENTS = {
    "\u2011": "-",  # Non-breaking hyphen
    "\u2010": "-",  # Unicode hyphen
    "\u00AD": "-",  # Soft hyphen
    "\u2012": "-",  # Figure dash
    "\u2212": "-",  # Minus sign
    "\uFE63": "-",  # Small hyphen-minus
    "\uFF0D": "-",  # Fullwidth hyphen-minus
    "\u2043": "-",  # Hyphen bullet
    "\u25A0": "-",  # Black square
    "\u25AA": "-",  # Black small square
    "\u25FE": "-",  # Black medium small square
    "\u25FD": "-",  # White medium small square
    "\u00A0": " ",  # Non-breaking space
    "\u202F": " ",  # Narrow no-break space
    "\u2007": " ",  # Figure space
    "\u2008": " ",  # Punctuation space
    "\u2009": " ",  # Thin space
    "\u200A": " ",  # Hair space
    "\u200B": "",   # Zero-width space
    "\uFEFF": "",   # Zero-width no-break space (BOM)
}


def normalize_typographic_punctuation(text: str) -> str:
    """Normalize typography control characters and non-standard hyphens to standard equivalents.

    Preserves Devanagari (U+0900-U+097F), Latin, numbers, and standard punctuation.
    Replaces font-incompatible non-breaking hyphens and missing glyphs with ASCII '-'.
    """
    if not text:
        return ""
    for bad, good in HYPHEN_REPLACEMENTS.items():
        text = text.replace(bad, good)
    return text


def build_pdf_script(declared_name: str, content: str) -> str:
    """Generate sandboxed Python script emitting a styled PDF via ReportLab."""
    cleaned_content = normalize_typographic_punctuation(content)
    escaped = json.dumps(cleaned_content)
    return (
        "import os, sys, json, re\n"
        "from reportlab.lib.pagesizes import letter\n"
        "from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle\n"
        "from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle\n"
        "from reportlab.lib import colors\n\n"
        "HYPHEN_MAP = {'\\u2011': '-', '\\u2010': '-', '\\u00AD': '-', '\\u2012': '-', "
        "'\\u2212': '-', '\\uFE63': '-', '\\uFF0D': '-', '\\u2043': '-', "
        "'\\u25A0': '-', '\\u25AA': '-', '\\u25FE': '-', '\\u25FD': '-', "
        "'\\u00A0': ' ', '\\u202F': ' ', '\\u200B': '', '\\uFEFF': ''}\n\n"
        "def clean_line(t):\n"
        "    if not t:\n"
        "        return ''\n"
        "    for k, v in HYPHEN_MAP.items():\n"
        "        t = t.replace(k, v)\n"
        "    if not (t.strip().startswith('|') and t.strip().endswith('|')):\n"
        "        t = re.sub(r'\\s*\\|\\s*$', '', t)\n"
        "    return t\n\n"
        "def main():\n"
        "    out_dir = os.environ.get('SWARAJ_OUT_DIR', './out')\n"
        "    os.makedirs(out_dir, exist_ok=True)\n"
        f"    out_path = os.path.join(out_dir, {json.dumps(declared_name)})\n"
        "    doc = SimpleDocTemplate(out_path, pagesize=letter, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)\n"
        "    styles = getSampleStyleSheet()\n"
        "    h1_style = ParagraphStyle('H1', parent=styles['Heading1'], fontSize=16, leading=20, textColor=colors.HexColor('#0B62D6'))\n"
        "    h2_style = ParagraphStyle('H2', parent=styles['Heading2'], fontSize=13, leading=17, textColor=colors.HexColor('#0B62D6'))\n"
        "    h3_style = ParagraphStyle('H3', parent=styles['Heading3'], fontSize=11, leading=15, textColor=colors.HexColor('#1F2328'))\n"
        "    body_style = ParagraphStyle('Body', parent=styles['Normal'], fontSize=10, leading=14, textColor=colors.HexColor('#1F2328'))\n"
        "    story = []\n"
        f"    raw_text = {escaped}\n"
        "    lines = raw_text.splitlines()\n"
        "    i = 0\n"
        "    while i < len(lines):\n"
        "        line = clean_line(lines[i])\n"
        "        trimmed = line.strip()\n"
        "        if not trimmed:\n"
        "            story.append(Spacer(1, 6))\n"
        "            i += 1\n"
        "            continue\n"
        "        if trimmed.startswith('# '):\n"
        "            story.append(Paragraph(trimmed[2:], h1_style))\n"
        "            story.append(Spacer(1, 8))\n"
        "        elif trimmed.startswith('## '):\n"
        "            story.append(Paragraph(trimmed[3:], h2_style))\n"
        "            story.append(Spacer(1, 6))\n"
        "        elif trimmed.startswith('### '):\n"
        "            story.append(Paragraph(trimmed[4:], h3_style))\n"
        "            story.append(Spacer(1, 4))\n"
        "        elif trimmed.startswith(('- ', '* ')):\n"
        "            clean_b = re.sub(r'\\*\\*(.+?)\\*\\*', r'<b>\\1</b>', trimmed[2:])\n"
        "            story.append(Paragraph(f'&bull; {clean_b}', body_style))\n"
        "            story.append(Spacer(1, 3))\n"
        "        elif re.match(r'^\\d+\\.\\s', trimmed):\n"
        "            clean_num = re.sub(r'\\*\\*(.+?)\\*\\*', r'<b>\\1</b>', trimmed)\n"
        "            story.append(Paragraph(clean_num, body_style))\n"
        "            story.append(Spacer(1, 3))\n"
        "        elif trimmed.startswith('|') and trimmed.endswith('|'):\n"
        "            table_data = []\n"
        "            while i < len(lines) and clean_line(lines[i]).strip().startswith('|') and clean_line(lines[i]).strip().endswith('|'):\n"
        "                row_str = clean_line(lines[i]).strip()\n"
        "                if not re.match(r'\\|[\\s\\-:]+\\|', row_str):\n"
        "                    cells = [c.strip() for c in row_str.strip('|').split('|')]\n"
        "                    p_cells = [Paragraph(re.sub(r'\\*\\*(.+?)\\*\\*', r'<b>\\1</b>', c), body_style) for c in cells]\n"
        "                    table_data.append(p_cells)\n"
        "                i += 1\n"
        "            if table_data:\n"
        "                t = Table(table_data)\n"
        "                t.setStyle(TableStyle([\n"
        "                    ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#F6F8FA')),\n"
        "                    ('BOTTOMPADDING', (0,0), (-1,-1), 4),\n"
        "                    ('TOPPADDING', (0,0), (-1,-1), 4),\n"
        "                    ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#D0D7DE')),\n"
        "                ]))\n"
        "                story.append(t)\n"
        "                story.append(Spacer(1, 8))\n"
        "            continue\n"
        "        else:\n"
        "            clean_p = re.sub(r'\\*\\*(.+?)\\*\\*', r'<b>\\1</b>', trimmed)\n"
        "            story.append(Paragraph(clean_p, body_style))\n"
        "            story.append(Spacer(1, 4))\n"
        "        i += 1\n"
        "    doc.build(story)\n\n"
        "if __name__ == '__main__':\n"
        "    main()\n"
    )


def build_docx_script(declared_name: str, content: str) -> str:
    """Generate sandboxed Python script emitting native DOCX elements with complex script support."""
    cleaned_content = normalize_typographic_punctuation(content)
    escaped = json.dumps(cleaned_content)
    return (
        "import os, sys, json, re\n"
        "from docx import Document\n"
        "from docx.shared import Inches, Pt, RGBColor\n"
        "from docx.oxml import OxmlElement\n"
        "from docx.oxml.ns import qn\n\n"
        "HYPHEN_MAP = {'\\u2011': '-', '\\u2010': '-', '\\u00AD': '-', '\\u2012': '-', "
        "'\\u2212': '-', '\\uFE63': '-', '\\uFF0D': '-', '\\u2043': '-', "
        "'\\u25A0': '-', '\\u25AA': '-', '\\u25FE': '-', '\\u25FD': '-', "
        "'\\u00A0': ' ', '\\u202F': ' ', '\\u200B': '', '\\uFEFF': ''}\n\n"
        "def clean_line(t):\n"
        "    if not t:\n"
        "        return ''\n"
        "    for k, v in HYPHEN_MAP.items():\n"
        "        t = t.replace(k, v)\n"
        "    if not (t.strip().startswith('|') and t.strip().endswith('|')):\n"
        "        t = re.sub(r'\\s*\\|\\s*$', '', t)\n"
        "    return t\n\n"
        "def apply_fonts(doc):\n"
        "    style = doc.styles['Normal']\n"
        "    style.font.name = 'Calibri'\n"
        "    style.font.size = Pt(11)\n"
        "    style.font.color.rgb = RGBColor(0x1F, 0x23, 0x28)\n"
        "    rPr = style.element.get_or_add_rPr()\n"
        "    rFonts = rPr.find(qn('w:rFonts'))\n"
        "    if rFonts is None:\n"
        "        rFonts = OxmlElement('w:rFonts')\n"
        "        rPr.append(rFonts)\n"
        "    rFonts.set(qn('w:ascii'), 'Calibri')\n"
        "    rFonts.set(qn('w:hAnsi'), 'Calibri')\n"
        "    rFonts.set(qn('w:cs'), 'Noto Sans Devanagari')\n\n"
        "def add_formatted_runs(p, text):\n"
        "    text = clean_line(text)\n"
        "    parts = re.split(r'(\\*\\*.*?\\*\\*)', text)\n"
        "    for part in parts:\n"
        "        if part.startswith('**') and part.endswith('**'):\n"
        "            r = p.add_run(part[2:-2])\n"
        "            r.bold = True\n"
        "        else:\n"
        "            p.add_run(part)\n\n"
        "def main():\n"
        "    out_dir = os.environ.get('SWARAJ_OUT_DIR', './out')\n"
        "    os.makedirs(out_dir, exist_ok=True)\n"
        f"    out_path = os.path.join(out_dir, {json.dumps(declared_name)})\n"
        "    doc = Document()\n"
        "    apply_fonts(doc)\n"
        "    for s in doc.sections:\n"
        "        s.top_margin = Inches(0.75)\n"
        "        s.bottom_margin = Inches(0.75)\n"
        "        s.left_margin = Inches(0.75)\n"
        "        s.right_margin = Inches(0.75)\n"
        f"    raw_text = {escaped}\n"
        "    lines = raw_text.splitlines()\n"
        "    i = 0\n"
        "    while i < len(lines):\n"
        "        line = clean_line(lines[i])\n"
        "        trimmed = line.strip()\n"
        "        if not trimmed:\n"
        "            i += 1\n"
        "            continue\n"
        "        if trimmed.startswith('# '):\n"
        "            h = doc.add_heading(level=1)\n"
        "            add_formatted_runs(h, trimmed[2:])\n"
        "            if h.runs:\n"
        "                h.runs[0].font.color.rgb = RGBColor(0x0B, 0x62, 0xD6)\n"
        "        elif trimmed.startswith('## '):\n"
        "            h = doc.add_heading(level=2)\n"
        "            add_formatted_runs(h, trimmed[3:])\n"
        "            if h.runs:\n"
        "                h.runs[0].font.color.rgb = RGBColor(0x0B, 0x62, 0xD6)\n"
        "        elif trimmed.startswith('### '):\n"
        "            h = doc.add_heading(level=3)\n"
        "            add_formatted_runs(h, trimmed[4:])\n"
        "        elif trimmed.startswith(('- ', '* ')):\n"
        "            p = doc.add_paragraph(style='List Bullet')\n"
        "            add_formatted_runs(p, trimmed[2:])\n"
        "        elif re.match(r'^\\d+\\.\\s', trimmed):\n"
        "            p = doc.add_paragraph()\n"
        "            add_formatted_runs(p, trimmed)\n"
        "        elif trimmed.startswith('|') and trimmed.endswith('|'):\n"
        "            table_lines = []\n"
        "            while i < len(lines) and clean_line(lines[i]).strip().startswith('|') and clean_line(lines[i]).strip().endswith('|'):\n"
        "                row_str = clean_line(lines[i]).strip()\n"
        "                if not re.match(r'\\|[\\s\\-:]+\\|', row_str):\n"
        "                    cells = [c.strip() for c in row_str.strip('|').split('|')]\n"
        "                    table_lines.append(cells)\n"
        "                i += 1\n"
        "            if table_lines:\n"
        "                cols = max(len(r) for r in table_lines)\n"
        "                tbl = doc.add_table(rows=len(table_lines), cols=cols)\n"
        "                tbl.style = 'Table Grid'\n"
        "                for r_idx, r_data in enumerate(table_lines):\n"
        "                    for c_idx, c_text in enumerate(r_data):\n"
        "                        if c_idx < cols:\n"
        "                            cell = tbl.rows[r_idx].cells[c_idx]\n"
        "                            cell.text = ''\n"
        "                            cp = cell.paragraphs[0]\n"
        "                            add_formatted_runs(cp, c_text)\n"
        "                            if r_idx == 0:\n"
        "                                for r in cp.runs:\n"
        "                                    r.bold = True\n"
        "            continue\n"
        "        else:\n"
        "            p = doc.add_paragraph()\n"
        "            add_formatted_runs(p, trimmed)\n"
        "        i += 1\n"
        "    doc.save(out_path)\n\n"
        "if __name__ == '__main__':\n"
        "    main()\n"
    )


def build_pptx_script(declared_name: str, content: str) -> str:
    """Generate sandboxed Python script emitting native PowerPoint slides via python-pptx."""
    cleaned_content = normalize_typographic_punctuation(content)
    escaped = json.dumps(cleaned_content)
    return (
        "import os, sys, json, re\n"
        "from pptx import Presentation\n"
        "from pptx.util import Inches, Pt\n"
        "from pptx.dml.color import RGBColor\n\n"
        "HYPHEN_MAP = {'\\u2011': '-', '\\u2010': '-', '\\u00AD': '-', '\\u2012': '-', "
        "'\\u2212': '-', '\\uFE63': '-', '\\uFF0D': '-', '\\u2043': '-', "
        "'\\u25A0': '-', '\\u25AA': '-', '\\u25FE': '-', '\\u25FD': '-', "
        "'\\u00A0': ' ', '\\u202F': ' ', '\\u200B': '', '\\uFEFF': ''}\n\n"
        "def clean_line(t):\n"
        "    if not t:\n"
        "        return ''\n"
        "    for k, v in HYPHEN_MAP.items():\n"
        "        t = t.replace(k, v)\n"
        "    return t\n\n"
        "def strip_md(t):\n"
        "    t = clean_line(t)\n"
        "    t = re.sub(r'\\*\\*(.+?)\\*\\*', r'\\1', t)\n"
        "    return t.strip()\n\n"
        "def main():\n"
        "    out_dir = os.environ.get('SWARAJ_OUT_DIR', './out')\n"
        "    os.makedirs(out_dir, exist_ok=True)\n"
        f"    out_path = os.path.join(out_dir, {json.dumps(declared_name)})\n"
        "    prs = Presentation()\n"
        "    prs.slide_width = Inches(13.333)\n"
        "    prs.slide_height = Inches(7.5)\n"
        f"    raw_text = {escaped}\n"
        "    lines = raw_text.splitlines()\n"
        "    blank_layout = prs.slide_layouts[6]\n"
        "    current_slide = None\n"
        "    current_tf = None\n"
        "    i = 0\n"
        "    while i < len(lines):\n"
        "        line = clean_line(lines[i])\n"
        "        trimmed = line.strip()\n"
        "        if not trimmed:\n"
        "            i += 1\n"
        "            continue\n"
        "        if trimmed.startswith('# ') and current_slide is None:\n"
        "            # Title slide\n"
        "            title_layout = prs.slide_layouts[0]\n"
        "            current_slide = prs.slides.add_slide(title_layout)\n"
        "            current_slide.shapes.title.text = strip_md(trimmed[2:])\n"
        "            current_tf = None\n"
        "        elif trimmed.startswith(('## ', '# ', '### ')):\n"
        "            # Content slide\n"
        "            heading_text = strip_md(re.sub(r'^#{1,3}\\s*', '', trimmed))\n"
        "            current_slide = prs.slides.add_slide(blank_layout)\n"
        "            # Add header\n"
        "            hb = current_slide.shapes.add_textbox(Inches(0.8), Inches(0.6), Inches(11.7), Inches(0.8))\n"
        "            hp = hb.text_frame.paragraphs[0]\n"
        "            hp.text = heading_text\n"
        "            hp.font.size = Pt(22)\n"
        "            hp.font.bold = True\n"
        "            hp.font.color.rgb = RGBColor(0x0B, 0x62, 0xD6)\n"
        "            # Add content textbox\n"
        "            cb = current_slide.shapes.add_textbox(Inches(0.8), Inches(1.6), Inches(11.7), Inches(5.0))\n"
        "            current_tf = cb.text_frame\n"
        "            current_tf.word_wrap = True\n"
        "        elif trimmed.startswith(('- ', '* ')):\n"
        "            if current_tf is None:\n"
        "                current_slide = prs.slides.add_slide(blank_layout)\n"
        "                cb = current_slide.shapes.add_textbox(Inches(0.8), Inches(1.0), Inches(11.7), Inches(5.5))\n"
        "                current_tf = cb.text_frame\n"
        "                current_tf.word_wrap = True\n"
        "            p = current_tf.add_paragraph() if current_tf.paragraphs and current_tf.paragraphs[0].text else current_tf.paragraphs[0]\n"
        "            p.text = f'• {strip_md(trimmed[2:])}'\n"
        "            p.font.size = Pt(14)\n"
        "            p.font.color.rgb = RGBColor(0x1F, 0x23, 0x28)\n"
        "        elif trimmed.startswith('|') and trimmed.endswith('|'):\n"
        "            table_lines = []\n"
        "            while i < len(lines) and clean_line(lines[i]).strip().startswith('|') and clean_line(lines[i]).strip().endswith('|'):\n"
        "                row_str = clean_line(lines[i]).strip()\n"
        "                if not re.match(r'\\|[\\s\\-:]+\\|', row_str):\n"
        "                    cells = [strip_md(c) for c in row_str.strip('|').split('|')]\n"
        "                    table_lines.append(cells)\n"
        "                i += 1\n"
        "            if table_lines:\n"
        "                if current_slide is None:\n"
        "                    current_slide = prs.slides.add_slide(blank_layout)\n"
        "                cols = max(len(r) for r in table_lines)\n"
        "                t_shape = current_slide.shapes.add_table(len(table_lines), cols, Inches(0.8), Inches(2.2), Inches(11.7), Inches(3.5))\n"
        "                tbl = t_shape.table\n"
        "                for r_idx, r_data in enumerate(table_lines):\n"
        "                    for c_idx, c_text in enumerate(r_data):\n"
        "                        if c_idx < cols:\n"
        "                            tbl.cell(r_idx, c_idx).text = c_text\n"
        "            continue\n"
        "        else:\n"
        "            if current_tf is None:\n"
        "                current_slide = prs.slides.add_slide(blank_layout)\n"
        "                cb = current_slide.shapes.add_textbox(Inches(0.8), Inches(1.0), Inches(11.7), Inches(5.5))\n"
        "                current_tf = cb.text_frame\n"
        "                current_tf.word_wrap = True\n"
        "            p = current_tf.add_paragraph() if current_tf.paragraphs and current_tf.paragraphs[0].text else current_tf.paragraphs[0]\n"
        "            p.text = strip_md(trimmed)\n"
        "            p.font.size = Pt(13)\n"
        "            p.font.color.rgb = RGBColor(0x1F, 0x23, 0x28)\n"
        "        i += 1\n"
        "    if len(prs.slides) == 0:\n"
        "        s = prs.slides.add_slide(blank_layout)\n"
        "        tb = s.shapes.add_textbox(Inches(1.0), Inches(1.0), Inches(11.3), Inches(4.0))\n"
        "        tb.text_frame.text = 'Presentation'\n"
        "    prs.save(out_path)\n\n"
        "if __name__ == '__main__':\n"
        "    main()\n"
    )

